# Generated by Django 5.2.10 on 2026-01-27 18:17

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('employer_payment', 'Employer Payment'), ('worker_disbursement', 'Worker Disbursement'), ('refund', 'Refund')], max_length=30)),
                ('external_reference', models.CharField(max_length=100, unique=True)),
                ('internal_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_provider', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('provider_status', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('total_contracts', models.IntegerField(default=0)),
                ('total_worker_salaries', models.BigIntegerField(default=0)),
                ('total_service_fees', models.BigIntegerField(default=0)),
                ('total_revenue', models.BigIntegerField(default=0)),
                ('invoices_generated', models.BooleanField(default=False)),
                ('payments_processed', models.BooleanField(default=False)),
                ('cycle_closed', models.BooleanField(default=False)),
                ('invoice_generation_date', models.DateTimeField(blank=True, null=True)),
                ('payment_processing_date', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payroll_cycles',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage'), ('tiered', 'Tiered')], default='fixed_amount', max_length=20)),
                ('fixed_amount', models.IntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tier_config', models.JSONField(blank=True, null=True)),
                ('minimum_fee', models.IntegerField(blank=True, null=True)),
                ('maximum_fee', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_fee_config',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_fee_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(max_length=50, unique=True)),
                ('salary_amount', models.IntegerField()),
                ('deductions', models.IntegerField(default=0)),
                ('net_amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_receipt_url', models.URLField(blank=True, null=True)),
                ('payslip_pdf_url', models.URLField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'worker_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('mobile_money_mtn', 'Mobile Money (MTN)'), ('mobile_money_airtel', 'Mobile Money (Airtel)'), ('bank_transfer', 'Bank Transfer'), ('cash_pickup', 'Cash Pickup')], max_length=50)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'worker_payment_methods',
            },
        ),
        migrations.CreateModel(
            name='EmployerInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('worker_salary_amount', models.IntegerField()),
                ('service_fee_amount', models.IntegerField()),
                ('additional_fees', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contracts.contract')),
            ],
            options={
                'db_table': 'employer_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
