# Generated by Django 5.2.10 on 2026-01-27 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employerinvoice',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.employerprofile'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.employerinvoice'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='payrollcycle',
            unique_together={('month', 'year')},
        ),
        migrations.AddField(
            model_name='employerinvoice',
            name='payroll_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.payrollcycle'),
        ),
        migrations.AddField(
            model_name='servicefeeconfig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_configs', to='users.jobcategory'),
        ),
        migrations.AddField(
            model_name='servicefeetransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_transactions', to='payments.employerinvoice'),
        ),
        migrations.AddField(
            model_name='servicefeetransaction',
            name='payroll_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_transactions', to='payments.payrollcycle'),
        ),
        migrations.AddField(
            model_name='workerpayment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_payments', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='workerpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_payments', to='payments.employerinvoice'),
        ),
        migrations.AddField(
            model_name='workerpayment',
            name='payroll_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_payments', to='payments.payrollcycle'),
        ),
        migrations.AddField(
            model_name='workerpayment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.workerprofile'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='worker_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.workerpayment'),
        ),
        migrations.AddField(
            model_name='workerpaymentmethod',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='users.workerprofile'),
        ),
        migrations.AddIndex(
            model_name='employerinvoice',
            index=models.Index(fields=['employer'], name='employer_in_employe_131b03_idx'),
        ),
        migrations.AddIndex(
            model_name='employerinvoice',
            index=models.Index(fields=['status'], name='employer_in_status_9f01f7_idx'),
        ),
        migrations.AddIndex(
            model_name='employerinvoice',
            index=models.Index(fields=['due_date'], name='employer_in_due_dat_abe9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='employerinvoice',
            index=models.Index(fields=['payroll_cycle'], name='employer_in_payroll_afc21c_idx'),
        ),
        migrations.AddIndex(
            model_name='employerinvoice',
            index=models.Index(fields=['invoice_number'], name='employer_in_invoice_b81bac_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeeconfig',
            index=models.Index(fields=['category', 'is_active'], name='service_fee_categor_5b8dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='workerpayment',
            index=models.Index(fields=['worker'], name='worker_paym_worker__80cb55_idx'),
        ),
        migrations.AddIndex(
            model_name='workerpayment',
            index=models.Index(fields=['status'], name='worker_paym_status_604c62_idx'),
        ),
        migrations.AddIndex(
            model_name='workerpayment',
            index=models.Index(fields=['scheduled_date'], name='worker_paym_schedul_acf8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='workerpayment',
            index=models.Index(fields=['payment_reference'], name='worker_paym_payment_d22ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['external_reference'], name='payment_tra_externa_28eafd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payment_tra_status_137fde_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['initiated_at'], name='payment_tra_initiat_02d485_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payer_user'], name='payment_tra_payer_u_36d990_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payee_user'], name='payment_tra_payee_u_e2f8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='workerpaymentmethod',
            index=models.Index(fields=['worker'], name='worker_paym_worker__056f72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workerpaymentmethod',
            unique_together={('worker', 'method_type', 'account_number')},
        ),
    ]
