# Generated by Django 5.2.10 on 2026-01-27 18:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('worker', 'Worker'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'Pending Verification')], default='pending_verification', max_length=25)),
                ('is_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PAYMENT', 'Payment'), ('VERIFICATION', 'Verification')], max_length=20)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(default='Kampala', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_verified', models.BooleanField(default=False)),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('business', 'Business')], default='basic', max_length=50)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employer_profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('city', models.CharField(default='Kampala', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('on_assignment', 'On Assignment')], default='available', max_length=20)),
                ('expected_salary_min', models.IntegerField(blank=True, null=True)),
                ('expected_salary_max', models.IntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('trust_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_placements', models.IntegerField(default=0)),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('pro', 'Pro')], default='basic', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worker_profiles',
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('identity', 'Identity'), ('background_check', 'Background Check'), ('reference', 'Reference'), ('skills_certification', 'Skills Certification'), ('medical', 'Medical')], max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='users.workerprofile')),
            ],
            options={
                'db_table': 'verifications',
            },
        ),
        migrations.CreateModel(
            name='WorkerReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referee_name', models.CharField(max_length=255)),
                ('referee_phone', models.CharField(max_length=20)),
                ('referee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_letter_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='users.workerprofile')),
            ],
            options={
                'db_table': 'worker_references',
            },
        ),
        migrations.CreateModel(
            name='WorkerSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('years_of_experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.jobcategory')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.workerprofile')),
            ],
            options={
                'db_table': 'worker_skills',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='users_status_9ca66f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='admin_activ_user_id_e9e042_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='admin_activ_entity__e444d3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='admin_activ_timesta_41920c_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['user'], name='employer_pr_user_id_fb9f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['city'], name='employer_pr_city_4d5bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['user'], name='worker_prof_user_id_df2160_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['verification_status'], name='worker_prof_verific_9a110a_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['availability'], name='worker_prof_availab_6608ba_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['city'], name='worker_prof_city_e14f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['rating_average'], name='worker_prof_rating__fc829d_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['worker'], name='verificatio_worker__83a763_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['status'], name='verificatio_status_40629d_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['verification_type'], name='verificatio_verific_da97c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workerskill',
            unique_together={('worker', 'skill_name')},
        ),
    ]
