# Generated by Django 5.2.10 on 2026-02-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workerprofile_completion_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='additional_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
