# Generated by Django 5.2.10 on 2026-02-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_workerprofile_additional_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('on_assignment', 'On Assignment'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('flexible', 'Flexible')], default='available', max_length=20),
        ),
    ]
