# Generated by Django 5.2.10 on 2026-02-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_workerprofile_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20, null=True),
        ),
    ]
