# Generated by Django 5.2.10 on 2026-01-27 18:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view_profile', 'View Profile'), ('view_job', 'View Job'), ('apply_job', 'Apply Job'), ('send_message', 'Send Message'), ('view_contract', 'View Contract'), ('make_payment', 'Make Payment'), ('post_job', 'Post Job'), ('update_profile', 'Update Profile'), ('search', 'Search')], max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_employers', models.PositiveIntegerField(default=0)),
                ('active_workers', models.PositiveIntegerField(default=0)),
                ('new_registrations', models.PositiveIntegerField(default=0)),
                ('new_employers', models.PositiveIntegerField(default=0)),
                ('new_workers', models.PositiveIntegerField(default=0)),
                ('active_contracts', models.PositiveIntegerField(default=0)),
                ('new_contracts', models.PositiveIntegerField(default=0)),
                ('completed_contracts', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_fees_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('worker_salaries_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_job_postings', models.PositiveIntegerField(default=0)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('application_to_hire_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trial_success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-metric_date'],
                'indexes': [models.Index(fields=['metric_date'], name='analytics_p_metric__c0d66f_idx')],
            },
        ),
    ]
