# Generated by Django 5.2.10 on 2026-01-27 18:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('temporary', 'Temporary'), ('on_demand', 'On Demand')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('trial', 'Trial'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('worker_salary_amount', models.IntegerField()),
                ('service_fee_amount', models.IntegerField()),
                ('total_monthly_cost', models.IntegerField()),
                ('payment_frequency', models.CharField(default='monthly', max_length=50)),
                ('start_date', models.DateField()),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('work_location', models.TextField(blank=True, null=True)),
                ('work_hours_per_week', models.IntegerField(default=40)),
                ('work_schedule', models.JSONField(default=dict)),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_duration_days', models.IntegerField(default=14)),
                ('trial_passed', models.BooleanField(blank=True, null=True)),
                ('trial_feedback', models.TextField(blank=True, null=True)),
                ('contract_document_url', models.URLField(blank=True, null=True)),
                ('signed_by_employer', models.BooleanField(default=False)),
                ('signed_by_worker', models.BooleanField(default=False)),
                ('employer_signature_date', models.DateTimeField(blank=True, null=True)),
                ('worker_signature_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('signature_data_employer', models.TextField(blank=True, null=True)),
                ('signature_data_worker', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('amendment', 'Amendment'), ('termination', 'Termination'), ('other', 'Other')], max_length=20)),
                ('document_url', models.URLField()),
                ('document_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractReplacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('is_free_replacement', models.BooleanField(default=True)),
                ('replacement_fee', models.IntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract_replacements',
                'ordering': ['-requested_at'],
            },
        ),
    ]
