# Generated by Django 5.2.10 on 2026-01-27 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='users.jobcategory'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='users.employerprofile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='users.workerprofile'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractreplacement',
            name='new_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_from', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractreplacement',
            name='original_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractreplacement',
            name='original_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_replacements', to='users.workerprofile'),
        ),
        migrations.AddField(
            model_name='contractreplacement',
            name='replacement_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_contracts', to='users.workerprofile'),
        ),
        migrations.AddField(
            model_name='contractreplacement',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['employer'], name='contracts_employe_9ac22e_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['worker'], name='contracts_worker__44aa93_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_status_093df1_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['trial_end_date'], name='contracts_trial_e_d2240d_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date'], name='contracts_start_d_b96943_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='contracts_created_dd2b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractreplacement',
            index=models.Index(fields=['original_contract'], name='contract_re_origina_1f7bad_idx'),
        ),
        migrations.AddIndex(
            model_name='contractreplacement',
            index=models.Index(fields=['status'], name='contract_re_status_c40719_idx'),
        ),
        migrations.AddIndex(
            model_name='contractreplacement',
            index=models.Index(fields=['requested_at'], name='contract_re_request_909e7c_idx'),
        ),
    ]
