# Generated by Django 5.2.10 on 2026-01-27 18:17

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('police_check', 'Police Check Certificate'), ('reference_letter', 'Reference Letter'), ('certificate', 'Professional Certificate'), ('medical_report', 'Medical Report'), ('passport_photo', 'Passport Photo'), ('educational_certificate', 'Educational Certificate'), ('other', 'Other')], max_length=50, unique=True)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_expiry_date', models.BooleanField(default=True)),
                ('requires_document_number', models.BooleanField(default=True)),
                ('requires_issuing_authority', models.BooleanField(default=False)),
                ('allowed_file_types', models.JSONField(default=list, help_text='List of allowed file extensions')),
                ('max_file_size_mb', models.IntegerField(default=10, help_text='Maximum file size in MB')),
                ('use_ai_verification', models.BooleanField(default=True)),
                ('ai_service', models.CharField(choices=[('google_vision', 'Google Vision API'), ('aws_rekognition', 'AWS Rekognition'), ('manual', 'Manual Review')], default='google_vision', max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document Type Configuration',
                'verbose_name_plural': 'Document Type Configurations',
                'ordering': ['display_order', 'document_type'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_service_used', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('verification_result', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('police_check', 'Police Check Certificate'), ('reference_letter', 'Reference Letter'), ('certificate', 'Professional Certificate'), ('medical_report', 'Medical Report'), ('passport_photo', 'Passport Photo'), ('educational_certificate', 'Educational Certificate'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='worker_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('ai_ocr_result', models.JSONField(blank=True, null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_extracted_data', models.JSONField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
