# Generated by Django 5.2.10 on 2026-01-27 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerdocument',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.workerprofile'),
        ),
        migrations.AddField(
            model_name='documentverificationrequest',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='documents.workerdocument'),
        ),
        migrations.AddIndex(
            model_name='workerdocument',
            index=models.Index(fields=['worker', 'status'], name='documents_w_worker__0e8693_idx'),
        ),
        migrations.AddIndex(
            model_name='workerdocument',
            index=models.Index(fields=['document_type'], name='documents_w_documen_c6c390_idx'),
        ),
        migrations.AddIndex(
            model_name='workerdocument',
            index=models.Index(fields=['uploaded_at'], name='documents_w_uploade_a088db_idx'),
        ),
        migrations.AddIndex(
            model_name='workerdocument',
            index=models.Index(fields=['status', 'expiry_date'], name='documents_w_status_74b73d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workerdocument',
            unique_together={('worker', 'document_type', 'document_number')},
        ),
        migrations.AddIndex(
            model_name='documentverificationrequest',
            index=models.Index(fields=['document', 'status'], name='documents_d_documen_b0459d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverificationrequest',
            index=models.Index(fields=['requested_at'], name='documents_d_request_98b69e_idx'),
        ),
    ]
