# Generated by Django 5.2.10 on 2026-01-27 18:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('system', 'System'), ('payment', 'Payment'), ('contract', 'Contract'), ('message', 'Message'), ('application', 'Application'), ('review', 'Review'), ('verification', 'Verification'), ('security', 'Security'), ('reminder', 'Reminder')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.URLField(blank=True, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_sms', models.BooleanField(default=False)),
                ('sent_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('email_contracts', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_applications', models.BooleanField(default=True)),
                ('email_reviews', models.BooleanField(default=True)),
                ('email_verifications', models.BooleanField(default=True)),
                ('email_security', models.BooleanField(default=True)),
                ('email_promotions', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('sms_payments', models.BooleanField(default=True)),
                ('sms_contracts', models.BooleanField(default=True)),
                ('sms_verifications', models.BooleanField(default=True)),
                ('sms_security', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('push_payments', models.BooleanField(default=True)),
                ('push_contracts', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_applications', models.BooleanField(default=True)),
                ('push_reviews', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
